Repository stolostron/multiclusterhub-operator, pull requests merged in 2021-06, with the labels that each got.

#594 add create curator for admin role
  templates/multiclusterhub/base/rbac/clusterrole-admin-aggregate.yaml
Labels: approved, lgtm

#596 add missing permissions for foundation crds
  deploy/olm-catalog/multiclusterhub-operator/manifests/multiclusterhub-operator.clusterserviceversion.yaml
  deploy/role.yaml
  templates/multiclusterhub/base/rbac/clusterrole-admin-aggregate.yaml
  templates/multiclusterhub/base/rbac/clusterrole-clustermanageradmin-aggregate.yaml
  templates/multiclusterhub/base/rbac/clusterrole-edit-aggregate.yaml
  templates/multiclusterhub/base/rbac/clusterrole-view-aggregate.yaml
Labels: approved, lgtm

#601 Add PR Function Tests
  .github/workflows/pr-function-tests.yml
  Makefile
  build/subscriptions/hive-op.yaml
  build/subscriptions/subscription-op.yaml
  common/scripts/pull-request-function-test.sh
  common/scripts/update-image-manifest.sh
  mock-component-image/scripts/generate-mock-charts.py
  test/utils/resources.go
  test/utils/utils.go
Labels: approved, dco-signoff: yes, lgtm

#595 update clusterset permission in admin/edit
  templates/multiclusterhub/base/rbac/clusterrole-admin-aggregate.yaml
  templates/multiclusterhub/base/rbac/clusterrole-edit-aggregate.yaml
Labels: approved, lgtm

#606 changed to create or update
  pkg/webhook/setup.go
Labels: approved, dco-signoff: yes, lgtm

#607 Update to version 2.0.12
  COMPONENT_VERSION
  Makefile
  build/configmap-install/package.yaml
  deploy/kustomization.yaml
  deploy/olm-catalog/multiclusterhub-operator/manifests/multiclusterhub-operator.clusterserviceversion.yaml
  deploy/operator.yaml
  deploy/subscription.yaml
  image-manifests/2.0.12.json
  pkg/manifest/manifest_test.go
  version/version.go
Labels: approved, dco-signoff: yes, lgtm

#608 use service serving certificates to replace selfgeneration
  pkg/deploying/deployer.go
  pkg/foundation/webhook.go
  pkg/rendering/renderer.go
  templates/multiclusterhub/base/certificates/kustomization.yaml
  templates/multiclusterhub/base/certificates/ocm-webhook-secret.yaml
  templates/multiclusterhub/base/webhook/webhook-mutating-config.yaml
  templates/multiclusterhub/base/webhook/webhook-validating-config.yaml
Labels: approved, dco-signoff: yes, lgtm

#613 Update to version 2.2.5
  COMPONENT_VERSION
  Makefile
  build/configmap-install/package.yaml
  build/index-install/composite/kustomization.yaml
  build/index-install/non-composite/kustomization.yaml
  deploy/kustomization.yaml
  deploy/olm-catalog/multiclusterhub-operator/manifests/multiclusterhub-operator.clusterserviceversion.yaml
  deploy/operator.yaml
  deploy/subscription.yaml
  image-manifests/2.2.5.json
  pkg/controller/multiclusterhub/common_test.go
  pkg/manifest/manifest_test.go
  test/Makefile
  test/multiclusterhub_install_test/multiclusterhub_test.go
  test/multiclusterhub_update_test/multiclusterhub_test.go
  test/utils/utils.go
  version/version.go
Labels: approved, dco-signoff: yes

#611 enabel ocm apiservice TLS
  pkg/foundation/proxy_server.go
Labels: approved, dco-signoff: yes, lgtm

#614 fix that unable to update deployment/service/apiservice
  go.mod
  go.sum
  pkg/controller/multiclusterhub/common.go
  pkg/controller/multiclusterhub/common_test.go
  pkg/controller/multiclusterhub/multiclusterhub_controller_test.go
  pkg/foundation/foundation.go
  pkg/foundation/foundation_test.go
Labels: approved, dco-signoff: yes, lgtm

#615 Rename insights to PolicyReport
  mock-component-image/scripts/generate-mock-charts.py
  pkg/controller/multiclusterhub/status.go
  pkg/subscription/insights.go
  test/utils/utils.go
Labels: approved, dco-signoff: yes, lgtm

#616 remove ocm klusterlet cert secret
  pkg/foundation/ocm_controller.go
  pkg/foundation/proxy_server.go
  pkg/rendering/renderer.go
  pkg/utils/certificate.go
  pkg/utils/certificate_test.go
  pkg/utils/utils.go
  templates/multiclusterhub/base/certificates/kustomization.yaml
  templates/multiclusterhub/base/certificates/ocm-klusterlet-self-signed-secrets.yaml
  templates/multiclusterhub/base/kustomization.yaml
Labels: approved, dco-signoff: yes, lgtm

#618 adding cron job for nightly function tests and slack bot to report
  .github/workflows/nightly-cron-function-tests.yml
  Makefile
  common/scripts/nightly-full-function-test.sh
  common/scripts/slack-bot-message.sh
  common/scripts/update-image-manifest.sh
  test/multiclusterhub_install_test/multiclusterhub_test.go
  test/multiclusterhub_uninstall_test/multiclusterhub_test.go
  test/multiclusterhub_update_test/multiclusterhub_test.go
  test/resources/discoveryconfig.yaml
  test/utils/resources.go
  test/utils/utils.go
Labels: approved, dco-signoff: yes, lgtm

#619 Update to version 2.1.9
  COMPONENT_VERSION
  Makefile
  build/configmap-install/package.yaml
  build/index-install/composite/kustomization.yaml
  build/index-install/non-composite/kustomization.yaml
  deploy/kustomization.yaml
  deploy/olm-catalog/multiclusterhub-operator/manifests/multiclusterhub-operator.clusterserviceversion.yaml
  deploy/operator.yaml
  deploy/subscription.yaml
  image-manifests/2.1.9.json
  pkg/controller/multiclusterhub/common_test.go
  pkg/controller/multiclusterhub/upgrade_hub_self_mgmt_test.go
  pkg/manifest/manifest_test.go
  test/Makefile
  test/multiclusterhub_install_test/multiclusterhub_test.go
  test/multiclusterhub_update_test/multiclusterhub_test.go
  test/utils/utils.go
  version/version.go
Labels: approved, dco-signoff: yes, lgtm

#621 Set default mode in ocm webhook volume
  pkg/foundation/webhook.go
Labels: approved, dco-signoff: yes, lgtm
