Repository stolostron/multiclusterhub-operator, pull requests merged in 2023-03, with the labels that each got.

#985 Add back AppSub part that is not being picked up by bundle automation
  pkg/templates/charts/toggle/multicloud-operators-subscription/templates/multicluster-applications-clustermanagementaddon.yaml
Labels: approved, dco-signoff: yes

#986 operator conditions
  config/rbac/role.yaml
  controllers/multiclusterhub_controller.go
  controllers/multiclusterhub_controller_test.go
  go.mod
  go.sum
  hack/prereqs/kustomization.yaml
  hack/prereqs/oc.yaml
  main.go
  pkg/utils/operatorconditions.go
  pkg/utils/operatorconditions_test.go
Labels: lgtm, approved, do-not-merge/hold, dco-signoff: yes

#989 Add UserPreference clusterrole
  pkg/templates/charts/toggle/console/templates/console-userpreference-clusterrole.yaml
Labels: lgtm, approved, dco-signoff: yes

#983 Revert "Backport the spec.copyPolicyMetadata field for 2.6 (#977)"
  hack/scripts/currentCRDs.txt
Labels: lgtm, approved, dco-signoff: yes

#991 ACM-3319 bug-adding a reconcile to the operator logic
  controllers/multiclusterhub_controller.go
Labels: lgtm, approved, dco-signoff: yes

#993 Use console service account for userpreference auth
  pkg/templates/charts/toggle/console/templates/console-clusterrole.yaml
  pkg/templates/charts/toggle/console/templates/console-userpreference-clusterrole.yaml
Labels: lgtm, approved, dco-signoff: yes

#994 Add permission for the new multiclusterappsetreport
  pkg/templates/multiclusterhub/base/clusterrole-admin-aggregate.yaml
  pkg/templates/multiclusterhub/base/clusterrole-edit-aggregate.yaml
  pkg/templates/multiclusterhub/base/clusterrole-view-aggregate.yaml
  pkg/templates/multiclusterhub/base/multicluster-applications-rbac-aggregate-admin.yaml
  pkg/templates/multiclusterhub/base/multicluster-applications-rbac-aggregate-edit.yaml
  pkg/templates/multiclusterhub/base/multicluster-applications-rbac-aggregate-view.yaml
Labels: lgtm, approved, dco-signoff: yes

#996 Give console service account get auth for userpreference
  pkg/templates/charts/toggle/console/templates/console-clusterrole.yaml
Labels: lgtm, approved, dco-signoff: yes

#999 ACM-3846 Add functionality to git action to include Cluster Managemen…
  hack/bundle-automation/generate-bundles.py
Labels: lgtm, approved, dco-signoff: yes

#984 intial commit of adding a watch on mce
  api/v1/webhook_test.go
  controllers/multiclusterhub_controller.go
  controllers/multiclusterhub_controller_test.go
  main.go
Labels: lgtm, approved, dco-signoff: yes

#1001 ACM-4116 Edit Seach V2 descriptors
  pkg/templates/crds/search-v2-operator/search.open-cluster-management.io_searches.yaml
Labels: lgtm, approved, dco-signoff: yes

#1003 ACM-4120 Remove Search V1 CRDs from 2.8
  controllers/uninstall.go
Labels: lgtm, approved, dco-signoff: yes

#1004 Update Go to 1.20 and update modules
  .github/workflows/nightly-cron-function-tests.yml
  .github/workflows/pr-function-tests.yml
  Dockerfile
  build/Dockerfile.prow
  build/Dockerfile.test.prow
  bundle.Dockerfile
  bundle/manifests/multiclusterhub-operator.clusterserviceversion.yaml
  bundle/manifests/operator.open-cluster-management.io_multiclusterhubs.yaml
  bundle/metadata/annotations.yaml
  config/crd/bases/operator.open-cluster-management.io_multiclusterhubs.yaml
  go.mod
  go.sum
  test/function_tests/utils/utils.go
Labels: lgtm, approved, dco-signoff: yes

#1006 [release-2.6] Update Go to 1.20
  .github/workflows/nightly-cron-function-tests.yml
  .github/workflows/pr-function-tests.yml
  Dockerfile
  build/Dockerfile.prow
  build/Dockerfile.test.prow
  bundle.Dockerfile
  bundle/manifests/multiclusterhub-operator.clusterserviceversion.yaml
  bundle/manifests/operator.open-cluster-management.io_multiclusterhubs.yaml
  bundle/metadata/annotations.yaml
  config/crd/bases/operator.open-cluster-management.io_multiclusterhubs.yaml
  config/rbac/role.yaml
  config/webhook/manifests.yaml
  go.mod
Labels: lgtm, approved, dco-signoff: yes

#1005 [release-2.7] Update Go to 1.20
  .github/workflows/nightly-cron-function-tests.yml
  .github/workflows/pr-function-tests.yml
  Dockerfile
  build/Dockerfile.prow
  build/Dockerfile.test.prow
  bundle.Dockerfile
  bundle/manifests/multiclusterhub-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  go.mod
Labels: lgtm, approved, dco-signoff: yes
