Repository stolostron/multiclusterhub-operator, pull requests merged in 2023-08, with the labels that each got.

#1052 ACM-6192: Fix volsync deployment spacing
  pkg/rendering/renderer_test.go
  pkg/templates/charts/toggle/volsync-controller/templates/volsync-addon-controller-deployment.yaml
Labels: lgtm, approved, dco-signoff: yes

#1064 Update Velero CRDs and upgrade to OADP 1.2 channel
  pkg/rendering/renderer.go
  pkg/rendering/renderer_test.go
  pkg/templates/charts/toggle/cluster-backup/values.yaml
  pkg/templates/crds/cluster-backup/velero.io_backups.yaml
  pkg/templates/crds/cluster-backup/velero.io_restores.yaml
  pkg/templates/crds/cluster-backup/velero.io_schedules.yaml
Labels: lgtm, approved, dco-signoff: yes

#1063 ACM-6550: Remove configmap watch to reduce cache demands
  controllers/multiclusterhub_controller.go
Labels: lgtm, approved, dco-signoff: yes

#1067 hypershift default
  api/v1/multiclusterhub_methods.go
Labels: lgtm, approved, dco-signoff: yes

#1066 [Release-2.8] Update Velero CRDs and upgrade to OADP 1.2 channel
  pkg/rendering/renderer.go
  pkg/rendering/renderer_test.go
  pkg/templates/charts/toggle/cluster-backup/values.yaml
  pkg/templates/crds/cluster-backup/velero.io_backups.yaml
  pkg/templates/crds/cluster-backup/velero.io_restores.yaml
  pkg/templates/crds/cluster-backup/velero.io_schedules.yaml
Labels: lgtm, approved, dco-signoff: yes

#1065 [ACM-6677] Migrated Observability out of ACM bundle
  Dockerfile
  api/v1/methods_test.go
  api/v1/multiclusterhub_methods.go
  controllers/multiclusterhub_controller.go
  controllers/multiclusterhub_controller_test.go
  hack/bundle-automation/config.yaml
  pkg/templates/charts/toggle/multicluster-observability-operator/Chart.yaml
  pkg/templates/charts/toggle/multicluster-observability-operator/templates/manager-config_v1_configmap.yaml
  pkg/templates/charts/toggle/multicluster-observability-operator/templates/multicluster-observability-operator-clusterrole.yaml
  pkg/templates/charts/toggle/multicluster-observability-operator/templates/multicluster-observability-operator-clusterrolebinding.yaml
  pkg/templates/charts/toggle/multicluster-observability-operator/templates/multicluster-observability-operator-serviceaccount.yaml
  pkg/templates/charts/toggle/multicluster-observability-operator/templates/multicluster-observability-operator.yaml
  pkg/templates/charts/toggle/multicluster-observability-operator/templates/multicluster-observability-webhook-service_v1_service.yaml
  pkg/templates/charts/toggle/multicluster-observability-operator/values.yaml
  pkg/templates/crds/multicluster-observability-operator/core.observatorium.io_observatoria.yaml
  pkg/templates/crds/multicluster-observability-operator/observability.open-cluster-management.io_multiclusterobservabilities.yaml
  pkg/templates/crds/multicluster-observability-operator/observability.open-cluster-management.io_observabilityaddons.yaml
  pkg/utils/utils.go
  pkg/utils/utils_test.go
  test/unit-tests/resources.go
Labels: lgtm, approved, dco-signoff: yes

#1058 cluster-permission operator install
  .github/workflows/update-pregenerated-charts.yml
  Makefile.dev
  api/v1/methods_test.go
  api/v1/multiclusterhub_methods.go
  controllers/multiclusterhub_controller.go
  controllers/multiclusterhub_controller_test.go
  hack/bundle-automation/copy-charts.py
  hack/bundle-automation/copy-config.yaml
  pkg/templates/charts/toggle/cluster-permission/Chart.yaml
  pkg/templates/charts/toggle/cluster-permission/templates/cluster-permission-clusterrole.yaml
  pkg/templates/charts/toggle/cluster-permission/templates/cluster-permission-clusterrolebinding.yaml
  pkg/templates/charts/toggle/cluster-permission/templates/cluster-permission-serviceaccount.yaml
  pkg/templates/charts/toggle/cluster-permission/templates/cluster-permission.yaml
  pkg/templates/charts/toggle/cluster-permission/values.yaml
  pkg/templates/crds/cluster-permission/rbac.open-cluster-management.io_clusterpermissions.yaml
  pkg/utils/utils.go
  pkg/utils/utils_test.go
  sonar-project.properties
Labels: lgtm, approved, dco-signoff: yes

#1074 Update workflow PR assignees
  .github/workflows/regenerate-bundles-2.7.yml
  .github/workflows/regenerate-bundles-2.8.yml
  .github/workflows/regenerate-bundles.yml
  .github/workflows/update-pregenerated-charts.yml
Labels: lgtm, approved, dco-signoff: yes

#1088 Fixed clusterpermission chart location
  controllers/multiclusterhub_controller.go
Labels: lgtm, approved, dco-signoff: yes

#1094 Revert "Update Velero CRDs and upgrade to OADP 1.2 channel (#1066)"
  pkg/rendering/renderer.go
  pkg/rendering/renderer_test.go
  pkg/templates/charts/toggle/cluster-backup/values.yaml
  pkg/templates/crds/cluster-backup/velero.io_backups.yaml
  pkg/templates/crds/cluster-backup/velero.io_restores.yaml
  pkg/templates/crds/cluster-backup/velero.io_schedules.yaml
Labels: lgtm, approved, dco-signoff: yes

#1093 Upgrade client-go to v0.27.2 and controller-runtime to v0.15.0
  api/v1/multiclusterhub_webhook.go
  controllers/multiclusterhub_controller.go
  go.mod
  go.sum
  main.go
Labels: lgtm, approved, dco-signoff: yes

#1103 Resynced OWNERS file for release-2.6
  OWNERS
Labels: lgtm, approved, dco-signoff: yes

#1100 [Automated PR] Resynced OWNERS file for main
  OWNERS
Labels: lgtm, approved, dco-signoff: yes

#1102 Resynced OWNERS file for release-2.7
  OWNERS
Labels: lgtm, approved, dco-signoff: yes

#1101 Resynced OWNERS file for release-2.8
  OWNERS
Labels: dco-signoff: yes

#1104 Revert "Upgrade client-go to v0.27.2 and controller-runtime to v0.15.…
  api/v1/multiclusterhub_webhook.go
  controllers/multiclusterhub_controller.go
  go.mod
  go.sum
  main.go
Labels: lgtm, approved
