Repository stolostron/multiclusterhub-operator, pull requests merged in 2024-08, with the labels that each got.

#1641 ACM-13004 - remove velero crds from being reconciled by mch
  pkg/templates/crds/cluster-backup/velero.io_backups.yaml
  pkg/templates/crds/cluster-backup/velero.io_backupstoragelocations.yaml
  pkg/templates/crds/cluster-backup/velero.io_deletebackuprequests.yaml
  pkg/templates/crds/cluster-backup/velero.io_restores.yaml
  pkg/templates/crds/cluster-backup/velero.io_schedules.yaml
Labels: lgtm, approved, dco-signoff: yes

#1640 ACM-12999 - remove velero crds from being reconciled by mch
  pkg/templates/crds/cluster-backup/velero.io_backups.yaml
  pkg/templates/crds/cluster-backup/velero.io_backupstoragelocations.yaml
  pkg/templates/crds/cluster-backup/velero.io_deletebackuprequests.yaml
  pkg/templates/crds/cluster-backup/velero.io_restores.yaml
  pkg/templates/crds/cluster-backup/velero.io_schedules.yaml
Labels: lgtm, approved, dco-signoff: yes

#1642 Internalhubcomponent
  config/crd/internal/internal-hub-component.yaml
Labels: lgtm, approved, dco-signoff: yes

#1646 Updated OWNERS file
  .github/workflows/update-pregenerated-charts.yml
  OWNERS
Labels: lgtm, approved, dco-signoff: yes

#1645 [ACM-12523] Onboard siteconfig component
  api/v1/multiclusterhub_methods.go
  api/v1/multiclusterhub_methods_test.go
  config/rbac/role.yaml
  controllers/multiclusterhub_controller.go
  controllers/multiclusterhub_controller_test.go
  hack/bundle-automation/config.yaml
  pkg/templates/charts/toggle/siteconfig-operator/Chart.yaml
  pkg/templates/charts/toggle/siteconfig-operator/templates/siteconfig-controller-manager-clusterrole.yaml
  pkg/templates/charts/toggle/siteconfig-operator/templates/siteconfig-controller-manager-clusterrolebinding.yaml
  pkg/templates/charts/toggle/siteconfig-operator/templates/siteconfig-controller-manager-metrics-service_v1_service.yaml
  pkg/templates/charts/toggle/siteconfig-operator/templates/siteconfig-controller-manager-role.yaml
  pkg/templates/charts/toggle/siteconfig-operator/templates/siteconfig-controller-manager-rolebinding.yaml
  pkg/templates/charts/toggle/siteconfig-operator/templates/siteconfig-controller-manager-serviceaccount.yaml
  pkg/templates/charts/toggle/siteconfig-operator/templates/siteconfig-controller-manager.yaml
  pkg/templates/charts/toggle/siteconfig-operator/templates/siteconfig-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
  pkg/templates/charts/toggle/siteconfig-operator/values.yaml
  pkg/templates/crds/siteconfig-operator/siteconfig.open-cluster-management.io_clusterinstances.yaml
  pkg/templates/rbac_gen.go
  pkg/utils/utils.go
Labels: lgtm, approved, dco-signoff: yes

#1654 ACM-12881 - Support customizing local cluster name
  pkg/templates/charts/toggle/cluster-backup/templates/hub-backup-placementrule.yaml
Labels: lgtm, approved, dco-signoff: yes

#1655 [ACM-12523] Updated siteconfig branch ref to release-2.12
  hack/bundle-automation/config.yaml
Labels: lgtm, approved, dco-signoff: yes

#1649 [ACM-13066] Updated webhook validation logic
  api/v1/multiclusterhub_methods.go
  api/v1/multiclusterhub_webhook.go
  api/v1/multiclusterhub_webhook_test.go
  controllers/multiclusterhub_controller.go
Labels: lgtm, approved, dco-signoff: yes

#1658 update CRD to include user restore options
  pkg/templates/crds/cluster-backup/cluster.open-cluster-management.io_restores.yaml
Labels: lgtm, approved, dco-signoff: yes

#1660 Add hubTemplateOptions field to the Policy CRD
  pkg/templates/crds/grc/policy.open-cluster-management.io_policies.yaml
Labels: lgtm, approved, dco-signoff: yes

#1657 [release-2.10][ACM-13066] Updated webhook validation logic
  api/v1/multiclusterhub_methods.go
  api/v1/multiclusterhub_webhook.go
  api/v1/multiclusterhub_webhook_test.go
  controllers/multiclusterhub_controller.go
Labels: lgtm, approved, dco-signoff: yes

#1659 [release-2.9][ACM-13066] Updated webhook validation logic
  api/v1/multiclusterhub_methods.go
  api/v1/multiclusterhub_webhook.go
  api/v1/multiclusterhub_webhook_test.go
  controllers/multiclusterhub_controller.go
Labels: lgtm, approved, dco-signoff: yes

#1661 allow to pause backup schedule
  pkg/templates/crds/cluster-backup/cluster.open-cluster-management.io_backupschedules.yaml
Labels: lgtm, approved, dco-signoff: yes

#1665 [release-2.12] Readded invalid component logic in webhook
  api/v1/multiclusterhub_webhook.go
  api/v1/multiclusterhub_webhook_test.go
Labels: lgtm, approved, dco-signoff: yes

#1666 [release-2.11] Readded invalid component logic in webhook
  api/v1/multiclusterhub_webhook.go
  api/v1/multiclusterhub_webhook_test.go
Labels: lgtm, approved, dco-signoff: yes

#1668 fix typo in crd description for paused prop
  pkg/templates/crds/cluster-backup/cluster.open-cluster-management.io_backupschedules.yaml
Labels: lgtm, approved

#1675 fix(KONFLUX-3663): format PipelineRun files and upload SAST results
  .tekton/multiclusterhub-operator-acm-211-pull-request.yaml
  .tekton/multiclusterhub-operator-acm-211-push.yaml
Labels: lgtm, approved, dco-signoff: yes, ok-to-test

#1674 fix(KONFLUX-3663): format PipelineRun files and upload SAST results
  .tekton/multiclusterhub-operator-acm-210-pull-request.yaml
  .tekton/multiclusterhub-operator-acm-210-push.yaml
Labels: lgtm, approved, dco-signoff: yes, ok-to-test

#1678 GRC: Add the missing token creation privilege
  config/rbac/role.yaml
  pkg/templates/charts/toggle/grc/templates/grc-clusterrole.yaml
  pkg/templates/rbac_gen.go
Labels: lgtm, approved, dco-signoff: yes

#1690 [ACM-12784] Support managing internalhubcomponent in operator reconcile
  api/v1/multiclusterhub_types.go
  api/v1/zz_generated.deepcopy.go
  bundle.Dockerfile
  bundle/manifests/multiclusterhub-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/crd/bases/operator.open-cluster-management.io_internalhubcomponents.yaml
  config/rbac/role.yaml
  controllers/common.go
  controllers/multiclusterhub_controller.go
  controllers/multiclusterhub_controller_test.go
  pkg/templates/crds/internal/internal-hub-component.yaml
  pkg/templates/rbac_gen.go
Labels: lgtm, approved, dco-signoff: yes

#1695 update CRDs to use v0.16.1 controller-gen (https://issues.redhat.com/browse/ACM-13685)
  pkg/templates/crds/cluster-backup/cluster.open-cluster-management.io_backupschedules.yaml
  pkg/templates/crds/cluster-backup/cluster.open-cluster-management.io_restores.yaml
Labels: lgtm, approved, dco-signoff: yes
